FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN microdnf install -y python3.12 python3.12-pip gcc python3.12-devel libpq-devel && \
    microdnf clean all

WORKDIR /app
COPY requirements.txt .
RUN pip3.12 install --no-cache-dir -r requirements.txt

COPY app/ ./app/

ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["python3.12", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
